version: "3.8"
services:
  dcs-postgres:
    image: postgres:15.3-alpine
    container_name: pet-
    restart: always
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
    ports:
      - 5432:5432
    volumes:
      - ./data/postgres:/var/lib/postgresql/data