micronaut:
  application:
    name: pet-shop
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**
datasources:
  default:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/root?useTimezone=true&serverTimezone=UTC

    db-type: postgres
    username: root
    password: root
    jpa:
      hibernate:
        ddl-auto: update
        show-sql: false
        open-in-view: false